### ISSUE TITLE
APP BREAKING BUG: nether timestamp clears when going to stronghold

### ISSUE THREAD

**Issue by snuffalo** [johnpyp/speedrun-timer#1]
I was playing your mod with my son and when he got to the stronghold, the nether timestamp was removed. he started crying and now he's locked himself in his room and i can hear korean pop music coming from his speakers.

**Comment by johnpyp** [comment]
tell your son i'm sorry

**Comment by johnpyp** [comment]
Fixed

**Comment by snuffalo** [comment]
I can't speak highly enough of the developers for fixing this bug. My son and I have are closer now than ever before. Thank u @johnpyp you have made this quaint North Dakotan house a home once more <3
